Update gha workflows for rocm jobs

diff --git a/.github/workflows/_linux-build.yml b/.github/workflows/_linux-build.yml
--- a/.github/workflows/_linux-build.yml
+++ b/.github/workflows/_linux-build.yml
@@ -64,8 +64,7 @@ on:
 
 jobs:
   build:
-    # Don't run on forked repos
-    if: github.repository_owner == 'pytorch'
+    if: github.repository_owner == 'ROCmSoftwarePlatform'
     runs-on: ${{ inputs.runner }}
     timeout-minutes: 240
     outputs:
@@ -73,6 +72,7 @@ jobs:
       test-matrix: ${{ steps.filter.outputs.test-matrix }}
     steps:
       - name: Setup SSH (Click me for login details)
+        if: false
         uses: pytorch/test-infra/.github/actions/setup-ssh@main
         with:
           github-secret: ${{ secrets.GITHUB_TOKEN }}
@@ -89,11 +89,12 @@ jobs:
 
       - name: Calculate docker image
         id: calculate-docker-image
-        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
+        uses: ./.github/actions/calculate-rocm-docker-image
         with:
           docker-image-name: ${{ inputs.docker-image-name }}
 
       - name: Use following to pull public copy of the image
+        if: false
         id: print-ghcr-mirror
         env:
           ECR_DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
@@ -103,9 +104,16 @@ jobs:
           echo "docker pull ghcr.io/pytorch/ci-image:${tag/:/-}"
 
       - name: Pull docker image
-        uses: pytorch/test-infra/.github/actions/pull-docker-image@main
-        with:
-          docker-image: ${{ steps.calculate-docker-image.outputs.docker-image }}
+        shell: bash
+        env:
+          DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
+        run: |
+          set -e
+          # ignore output since only exit code is used for conditional
+          # only pull docker image if it's not available locally
+          if ! docker inspect --type=image "${DOCKER_IMAGE}" >/dev/null 2>/dev/null; then
+            docker pull "${DOCKER_IMAGE}"
+          fi
 
       - name: Parse ref
         id: parse-ref
@@ -128,6 +136,7 @@ jobs:
           job-name: ${{ steps.get-job-id.outputs.job-name }}
 
       - name: Download pytest cache
+        if: false
         uses: ./.github/actions/pytest-cache-download
         continue-on-error: true
         with:
@@ -141,12 +150,12 @@ jobs:
           BUILD_ENVIRONMENT: ${{ inputs.build-environment }}
           BRANCH: ${{ steps.parse-ref.outputs.branch }}
           # TODO duplicated
-          AWS_DEFAULT_REGION: us-east-1
+          # AWS_DEFAULT_REGION: us-east-1
           PR_NUMBER: ${{ github.event.pull_request.number }}
           SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
           SCCACHE_BUCKET: ossci-compiler-cache-circleci-v2
-          SCCACHE_S3_KEY_PREFIX: ${{ github.workflow }}
-          XLA_CLANG_CACHE_S3_BUCKET_NAME: ossci-compiler-clang-cache-circleci-xla
+          # SCCACHE_S3_KEY_PREFIX: ${{ github.workflow }}
+          # XLA_CLANG_CACHE_S3_BUCKET_NAME: ossci-compiler-clang-cache-circleci-xla
           PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
           TORCH_CUDA_ARCH_LIST: ${{ inputs.cuda-arch-list }}
           DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
@@ -159,14 +168,14 @@ jobs:
           container_name=$(docker run \
             -e BUILD_ENVIRONMENT \
             -e MAX_JOBS="$(nproc --ignore=2)" \
-            -e AWS_DEFAULT_REGION \
+            `# -e AWS_DEFAULT_REGION` \
             -e PR_NUMBER \
             -e SHA1 \
             -e BRANCH \
             -e SCCACHE_BUCKET \
-            -e SCCACHE_S3_KEY_PREFIX \
+            `# -e SCCACHE_S3_KEY_PREFIX` \
             -e XLA_CUDA \
-            -e XLA_CLANG_CACHE_S3_BUCKET_NAME \
+            `# -e XLA_CLANG_CACHE_S3_BUCKET_NAME` \
             -e SKIP_SCCACHE_INITIALIZATION=1 \
             -e TORCH_CUDA_ARCH_LIST \
             -e PR_LABELS \
@@ -177,7 +186,7 @@ jobs:
             --cap-add=SYS_PTRACE \
             --tty \
             --detach \
-            --user jenkins \
+            --user root \
             -v "${GITHUB_WORKSPACE}:/var/lib/jenkins/workspace" \
             -w /var/lib/jenkins/workspace \
             "${DOCKER_IMAGE}"
@@ -189,8 +198,8 @@ jobs:
         run: |
           zip -1 -r artifacts.zip dist/ build/custom_test_artifacts build/lib build/bin .additional_ci_files
 
-      - name: Store PyTorch Build Artifacts on S3
-        uses: seemethere/upload-artifact-s3@v5
+      - name: Store PyTorch Build Artifacts on GHA
+        uses: actions/upload-artifact@v4
         if: inputs.build-generates-artifacts && steps.build.outcome != 'skipped'
         with:
           name: ${{ inputs.build-environment }}
@@ -199,7 +208,7 @@ jobs:
           path: artifacts.zip
 
       - name: Upload sccache stats
-        if: steps.build.outcome != 'skipped'
+        if: false && steps.build.outcome != 'skipped'
         uses: seemethere/upload-artifact-s3@v5
         with:
           s3-prefix: |
@@ -211,3 +220,5 @@ jobs:
       - name: Teardown Linux
         uses: pytorch/test-infra/.github/actions/teardown-linux@main
         if: always()
+        with:
+          skip-wait-ssh: true
diff --git a/.github/workflows/_rocm-test.yml b/.github/workflows/_rocm-test.yml
--- a/.github/workflows/_rocm-test.yml
+++ b/.github/workflows/_rocm-test.yml
@@ -49,7 +49,7 @@ permissions:
 jobs:
   test:
     # Don't run on forked repos or empty test matrix
-    if: github.repository_owner == 'pytorch' && toJSON(fromJSON(inputs.test-matrix).include) != '[]'
+    if: github.repository_owner == 'ROCmSoftwarePlatform' && toJSON(fromJSON(inputs.test-matrix).include) != '[]'
     strategy:
       matrix: ${{ fromJSON(inputs.test-matrix) }}
       fail-fast: false
@@ -66,6 +66,7 @@ jobs:
         uses: ./.github/actions/setup-rocm
 
       - name: configure aws credentials
+        if: false
         id: aws_creds
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -74,20 +75,28 @@ jobs:
           role-duration-seconds: 18000
 
       - name: Login to Amazon ECR
+        if: false
         id: login-ecr
         continue-on-error: true
         uses: aws-actions/amazon-ecr-login@v2
 
       - name: Calculate docker image
         id: calculate-docker-image
-        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
+        uses: ./.github/actions/calculate-rocm-docker-image
         with:
           docker-image-name: ${{ inputs.docker-image }}
 
       - name: Pull docker image
-        uses: pytorch/test-infra/.github/actions/pull-docker-image@main
-        with:
-          docker-image: ${{ steps.calculate-docker-image.outputs.docker-image }}
+        shell: bash
+        env:
+          DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
+        run: |
+          set -e
+          # ignore output since only exit code is used for conditional
+          # only pull docker image if it's not available locally
+          if ! docker inspect --type=image "${DOCKER_IMAGE}" >/dev/null 2>/dev/null; then
+            docker pull "${DOCKER_IMAGE}"
+          fi
 
       - name: Start monitoring script
         id: monitor-script
@@ -102,8 +111,10 @@ jobs:
         uses: ./.github/actions/download-build-artifacts
         with:
           name: ${{ inputs.build-environment }}
+          use-gha: true
 
       - name: Download TD artifacts
+        if: false
         continue-on-error: true
         uses: ./.github/actions/download-td-artifacts
 
@@ -152,7 +163,7 @@ jobs:
           JOB_NAME: ${{ steps.get-job-id.outputs.job-name }}
           BRANCH: ${{ steps.parse-ref.outputs.branch }}
           SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
-          CONTINUE_THROUGH_ERROR: ${{ steps.keep-going.outputs.keep-going }}
+          CONTINUE_THROUGH_ERROR: True # ${{ steps.keep-going.outputs.keep-going }}
           VERBOSE_TEST_LOGS: ${{ steps.keep-going.outputs.ci-verbose-test-logs }}
           NO_TEST_TIMEOUT: ${{ steps.keep-going.outputs.ci-no-test-timeout }}
           NO_TD: ${{ steps.keep-going.outputs.ci-no-td }}
@@ -160,9 +171,9 @@ jobs:
           SHARD_NUMBER: ${{ matrix.shard }}
           NUM_TEST_SHARDS: ${{ matrix.num_shards }}
           REENABLED_ISSUES: ${{ steps.keep-going.outputs.reenabled-issues }}
-          SCCACHE_BUCKET: ossci-compiler-cache-circleci-v2
+          # SCCACHE_BUCKET: ossci-compiler-cache-circleci-v2
           DOCKER_IMAGE: ${{ inputs.docker-image }}
-          XLA_CLANG_CACHE_S3_BUCKET_NAME: ossci-compiler-clang-cache-circleci-xla
+          # XLA_CLANG_CACHE_S3_BUCKET_NAME: ossci-compiler-clang-cache-circleci-xla
           PYTORCH_TEST_CUDA_MEM_LEAK_CHECK: ${{ matrix.mem_leak_check && '1' || '0' }}
           PYTORCH_TEST_RERUN_DISABLED_TESTS: ${{ matrix.rerun_disabled_tests && '1' || '0' }}
           TESTS_TO_INCLUDE: ${{ inputs.tests-to-include }}
@@ -197,7 +208,7 @@ jobs:
             -e JOB_NAME \
             -e BRANCH \
             -e SHA1 \
-            -e AWS_DEFAULT_REGION \
+            `# -e AWS_DEFAULT_REGION` \
             -e IN_WHEEL_TEST \
             -e SHARD_NUMBER \
             -e TEST_CONFIG \
@@ -208,8 +219,8 @@ jobs:
             -e NO_TEST_TIMEOUT \
             -e NO_TD \
             -e MAX_JOBS="$(nproc --ignore=2)" \
-            -e SCCACHE_BUCKET \
-            -e XLA_CLANG_CACHE_S3_BUCKET_NAME \
+            `# -e SCCACHE_BUCKET` \
+            `# -e XLA_CLANG_CACHE_S3_BUCKET_NAME` \
             -e PYTORCH_TEST_CUDA_MEM_LEAK_CHECK \
             -e PYTORCH_TEST_RERUN_DISABLED_TESTS \
             -e TESTS_TO_INCLUDE \
@@ -222,7 +233,7 @@ jobs:
             --tty \
             --detach \
             --name="${container_name}" \
-            --user jenkins \
+            --user root \
             -v "${GITHUB_WORKSPACE}:/var/lib/jenkins/workspace" \
             -w /var/lib/jenkins/workspace \
             "${DOCKER_IMAGE}"
